language: node_js
node_js:
  - "8"
  - '7'
  - '6'
os: linux
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  yarn: true
branches:
  only:
    - master
install:
- |
    yarn install
script:
- |
    yarn lint && yarn test
after_success:
- |
    cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/codecov
