language: node_js
node_js:
  - "7"
  - "8"
os: linux
cache:
  yarn: true
branches:
  only:
    - master
install:
- |
    yarn install
script:
- |
    yarn lint && yarn test
after_success:
- |
    cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/codecov
